
// Single source of truth for currency data
export const currencyData = {
  USD: { name: "US Dollar", flag: "🇺🇸" },
  EUR: { name: "Euro", flag: "🇪🇺" },
  GBP: { name: "British Pound", flag: "🇬🇧" },
  JPY: { name: "Japanese Yen", flag: "🇯🇵" },
  CAD: { name: "Canadian Dollar", flag: "🇨🇦" },
  AUD: { name: "Australian Dollar", flag: "🇦🇺" },
  CHF: { name: "Swiss Franc", flag: "🇨🇭" },
  CNY: { name: "Chinese Yuan", flag: "🇨🇳" },
  INR: { name: "Indian Rupee", flag: "🇮🇳" },
  KRW: { name: "South Korean Won", flag: "🇰🇷" },
  SGD: { name: "Singapore Dollar", flag: "🇸🇬" },
  HKD: { name: "Hong Kong Dollar", flag: "🇭🇰" },
  NOK: { name: "Norwegian Krone", flag: "🇳🇴" },
  SEK: { name: "Swedish Krona", flag: "🇸🇪" },
  DKK: { name: "Danish Krone", flag: "🇩🇰" },
  PLN: { name: "Polish Zloty", flag: "🇵🇱" },
  CZK: { name: "Czech Koruna", flag: "🇨🇿" },
  HUF: { name: "Hungarian Forint", flag: "🇭🇺" },
  RUB: { name: "Russian Ruble", flag: "🇷🇺" },
  BRL: { name: "Brazilian Real", flag: "🇧🇷" },
  MXN: { name: "Mexican Peso", flag: "🇲🇽" },
  ZAR: { name: "South African Rand", flag: "🇿🇦" },
  NZD: { name: "New Zealand Dollar", flag: "🇳🇿" },
  TRY: { name: "Turkish Lira", flag: "🇹🇷" },
  AED: { name: "UAE Dirham", flag: "🇦🇪" },
  THB: { name: "Thai Baht", flag: "🇹🇭" },
  MYR: { name: "Malaysian Ringgit", flag: "🇲🇾" },
  IDR: { name: "Indonesian Rupiah", flag: "🇮🇩" },
  PHP: { name: "Philippine Peso", flag: "🇵🇭" },
  VND: { name: "Vietnamese Dong", flag: "🇻🇳" },
  ILS: { name: "Israeli Shekel", flag: "🇮🇱" },
  EGP: { name: "Egyptian Pound", flag: "🇪🇬" },
  SAR: { name: "Saudi Riyal", flag: "🇸🇦" },
  QAR: { name: "Qatari Riyal", flag: "🇶🇦" },
  KWD: { name: "Kuwaiti Dinar", flag: "🇰🇼" },
  BHD: { name: "Bahraini Dinar", flag: "🇧🇭" },
  OMR: { name: "Omani Rial", flag: "🇴🇲" },
  JOD: { name: "Jordanian Dinar", flag: "🇯🇴" },
  LBP: { name: "Lebanese Pound", flag: "🇱🇧" },
  RON: { name: "Romanian Leu", flag: "🇷🇴" },
  BGN: { name: "Bulgarian Lev", flag: "🇧🇬" },
  HRK: { name: "Croatian Kuna", flag: "🇭🇷" },
  RSD: { name: "Serbian Dinar", flag: "🇷🇸" },
  ISK: { name: "Icelandic Krona", flag: "🇮🇸" },
  CLP: { name: "Chilean Peso", flag: "🇨🇱" },
  PEN: { name: "Peruvian Sol", flag: "🇵🇪" },
  COP: { name: "Colombian Peso", flag: "🇨🇴" },
  ARS: { name: "Argentine Peso", flag: "🇦🇷" },
  UYU: { name: "Uruguayan Peso", flag: "🇺🇾" },
  TWD: { name: "Taiwan Dollar", flag: "🇹🇼" },
  UAH: { name: "Ukrainian Hryvnia", flag: "🇺🇦" },
  KZT: { name: "Kazakhstani Tenge", flag: "🇰🇿" },
  MAD: { name: "Moroccan Dirham", flag: "🇲🇦" },
  TND: { name: "Tunisian Dinar", flag: "🇹🇳" },
  KES: { name: "Kenyan Shilling", flag: "🇰🇪" },
  GHS: { name: "Ghanaian Cedi", flag: "🇬🇭" },
  NGN: { name: "Nigerian Naira", flag: "🇳🇬" },
  ETB: { name: "Ethiopian Birr", flag: "🇪🇹" },
};

export const majorCurrencies = [
  "USD", "EUR", "GBP", "JPY", "CAD", "AUD", "CHF", "CNY", "INR", "KRW", 
  "SGD", "HKD", "NOK", "SEK", "DKK", "PLN", "CZK", "HUF", "RUB", "BRL", 
  "MXN", "ZAR", "NZD", "TRY", "AED", "THB", "MYR", "IDR", "PHP", "VND", 
  "ILS", "EGP", "SAR", "QAR", "KWD", "BHD", "OMR", "JOD", "LBP",
];
